master: precommit fixed

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,6 +1,7 @@
 #!/bin/bash
 cd "$(git rev-parse --show-toplevel)"
 ESLINT="node_modules/.bin/eslint"
+CLIENT_ESLINT="./client/node_modules/.bin/eslint"
 pwd
 
 if [[ ! -x "$ESLINT" ]]; then
@@ -8,22 +9,40 @@ if [[ ! -x "$ESLINT" ]]; then
   exit 1
 fi
 
-STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$"))
+SERVER_FILES=($(git diff --cached --name-only --diff-filter=ACM ./server | grep ".jsx\{0,1\}$"))
+CLIENT_FILES=($(git diff --cached --name-only --diff-filter=ACM ./client | grep -E "(.css)|(.scss)|(.vue)|(.jsx{0,1})"))
 
-echo "ESLint'ing ${#STAGED_FILES[@]} files"
+echo "ESLint'ing ${#SERVER_FILES[@]} files"
 
-if [[ "$STAGED_FILES" = "" ]]; then
+if [[ "$SERVER_FILES" != "" ]]; then
+
+	$ESLINT "${SERVER_FILES[@]}" --fix
+	ESLINT_EXIT="$?"
+
+# Re-add files since they may have been fixed
+	git add "${SERVER_FILES[@]}"
+
+	if [[ "${ESLINT_EXIT}" == 0 ]]; then
+		printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
+	else
+		printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
+		exit 1
+	fi
+
+fi
+
+echo "ESLint'ing ${#CLIENT_FILES[@]} files"
+
+if [[ "$CLIENT_FILES" = "" ]]; then
   exit 0
 fi
 
-$ESLINT "${STAGED_FILES[@]}" --fix
-
-ESLINT_EXIT="$?"
+$CLIENT_ESLINT --resolve-plugins-relative-to "client/" "${CLIENT_FILES[@]}" --fix
+CLIENT_ESLINT_EXIT="$?"
 
 # Re-add files since they may have been fixed
-git add "${STAGED_FILES[@]}"
-
-if [[ "${ESLINT_EXIT}" == 0 ]]; then
+git add "${CLIENT_FILES[@]}"
+if [[ "${CLIENT_ESLINT_EXIT}" == 0 ]]; then
   printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
 else
   printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
